name: Build Flutter APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'
          
      - run: sed -i '/mockito:/d' pubspec.yaml
      
      - run: flutter clean
      # --- 新增下面这两行，解决 AndroidX 依赖冲突 ---
      - run: |
          echo "android.useAndroidX=true" > android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
      # ------------------------------------------
      
      - run: flutter pub get
      
      # 使用 | 符号来解决 YAML 的格式冲突
      - run: |
          sed -i '/apply from: "$flutterRoot\/packages\/flutter_tools\/gradle\/flutter.gradle"/a tasks.whenTaskAdded { task -> if (task.name.contains("stripReleaseDebugSymbols")) { task.enabled = false } }' android/app/build.gradle
      
      - run: flutter build apk --release --no-tree-shake-icons --no-sound-null-safety
      
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
